project:
  type: website
  output-dir: docs

website:
  title: "Synergetic Healing"
  navbar:
    left:
      - href: courses.qmd

format:
  html:
    theme: yeti
    css: assets/styles.css
    toc: true

editor: visual

